version: "2.2"
volumes:
  data:
  config:
  plugin:
networks:
  es:
services:
  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "es"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data:/usr/share/elasticsearch/data
      - config:/ust/share/elasticsearch/config
      - plugin:/ust/share/elasticsearch/plugins
  kibana:
    image: kibana:7.6.0
    ports:
      - "5601:5601"
    networks:
      - "es"
    volumes:
      - /elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml